# -*- coding: utf-8 -*-
"""031-Python in a minute.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/14Idgyx6n3ka0QnMyD0TWqNW5r1OGkE06
"""

# Code Example 1: Basic Usage
my_string = "hello, world!"
print(my_string.capitalize())  # Output: "Hello, world!"

# Code Example 2: All Uppercase
shouting_string = "PYTHON IS GREAT!"
print(shouting_string.capitalize())  # Output: "Python is great!"

# Code Example 3: Mixed Case
mixed_case_string = "pYtHoN pRoGrAmMiNg"
print(mixed_case_string.capitalize())  # Output: "Python programming"