# -*- coding: utf-8 -*-
"""032-Python in a minute.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1JSLOG4AHSfBxGUDzHVF0uHdc-Ent6U_x
"""

# Code Example 1: Basic Usage
my_string = "Hello, World!"
print(my_string.casefold())  # Output: "hello, world!"

# Code Example 2: Comparison with lower()
mixed_case_string = "Straße"
print(mixed_case_string.lower())     # Output: "straße"
print(mixed_case_string.casefold())  # Output: "strasse"

# Code Example 3: International Characters
turkish_string = "İstanbul"
print(turkish_string.casefold())  # Output: "istanbul"