# -*- coding: utf-8 -*-
"""034-Python in a minute.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1fWXZes1ENYTNpbOmax23Wy8LZdvMPrw0
"""

from IPython.display import HTML
shell = get_ipython()

def adjust_font_size():
  display(HTML('''<style>
    body {
      font-size: 28px;
    }
  '''))

if adjust_font_size not in shell.events.callbacks['pre_execute']:
  shell.events.register('pre_execute', adjust_font_size)

# Code Example 1: Basic Usage
my_string = "Hello, World! Hello, everyone!"
print(my_string.count("Hello"))  # Output: 2

# Code Example 2: With Start and End Parameters
print(my_string.count("Hello", 0, 12))  # Output: 1

# Code Example 3: Case Sensitivity
print(my_string.count("hello"))  # Output: 0