# -*- coding: utf-8 -*-
"""035-Python in a minute.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1UGeQH0TtgWJaTQMfwVFeb4JiFxjit8nx
"""

from IPython.display import HTML
shell = get_ipython()

def adjust_font_size():
  display(HTML('''<style>
    body {
      font-size: 28px;
    }
  '''))

if adjust_font_size not in shell.events.callbacks['pre_execute']:
  shell.events.register('pre_execute', adjust_font_size)

# Sample string
text = "Hello, Python!"

# Encoding the string
encoded_text = text.encode()

print(encoded_text)  # Output: b'Hello, Python!'

# Specifying a different encoding
encoded_text = text.encode('ascii')

print(encoded_text)  # Output: b'Hello, Python!'

# String with non-ASCII character
text_with_non_ascii = "Hello, Python! 🌟"

try:
    # Attempt to encode with 'ascii'
    encoded_text = text_with_non_ascii.encode('ascii')
except UnicodeEncodeError as e:
    print(f"Encoding error: {e}")

# Using 'ignore' to skip errors
encoded_text_ignore = text_with_non_ascii.encode('ascii', errors='ignore')
print(encoded_text_ignore)  # Output: b'Hello, Python! '

# Using 'replace' to replace errors with a placeholder
encoded_text_replace = text_with_non_ascii.encode('ascii', errors='replace')
print(encoded_text_replace)  # Output: b'Hello, Python! ?'