# -*- coding: utf-8 -*-
"""036-Python in a minute.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1mMzvfDHzVvFjd2Yy5NrMGsS2r8EAD5ZB
"""

from IPython.display import HTML
shell = get_ipython()

def adjust_font_size():
  display(HTML('''<style>
    body {
      font-size: 28px;
    }
  '''))

if adjust_font_size not in shell.events.callbacks['pre_execute']:
  shell.events.register('pre_execute', adjust_font_size)

# Sample filename
filename = "photo.png"

# Check if the filename ends with ".png"
result = filename.endswith(".png")
print(result)  # Output: True

# Check if the filename ends with ".jpg"
result = filename.endswith(".jpg")
print(result)  # Output: False

# Sample filename with path
filepath = "/user/music/song.mp3"

# Check if the substring from index 11 to end ends with ".mp3"
result = filepath.endswith(".mp3", 11)
print(result)  # Output: True

# Check if the substring from index 0 to 9 ends with ".png"
result = filepath.endswith(".png", 0, 9)
print(result)  # Output: False