# -*- coding: utf-8 -*-
"""037-Python in a minute.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1dA8cBxKzs34QaTSH5nKT-7YNYY0NqT4d
"""

from IPython.display import HTML
shell = get_ipython()

def adjust_font_size():
  display(HTML('''<style>
    body {
      font-size: 28px;
    }
  '''))

if adjust_font_size not in shell.events.callbacks['pre_execute']:
  shell.events.register('pre_execute', adjust_font_size)

# Sample string with tabs

text = "Hello\tPython!"

# Expanding tabs with default tab size (8 spaces)

expanded_text = text.expandtabs()
print(expanded_text)  # Output: 'Hello   Python!'

# Expanding tabs with tab size of 4 spaces

expanded_text = text.expandtabs(4)
print(expanded_text)  # Output: 'Hello   Python!'

# String with multiple tabs

text_with_tabs = "Hello\tworld!\tPython\tis\tgreat!"

# Expanding tabs with default tab size (8 spaces)

expanded_text_default = text_with_tabs.expandtabs()
print(expanded_text_default)
# Output: 'Hello   world!  Python  is      great!'

# Expanding tabs with tab size of 4 spaces

expanded_text_4 = text_with_tabs.expandtabs(4)
print(expanded_text_4)
# Output: 'Hello   world!  Python  is  great!'