# -*- coding: utf-8 -*-
"""038-Python in a minute.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1VNHjjEP2idunjcIa-4xlrarDwdpA7H2e
"""

from IPython.display import HTML
shell = get_ipython()

def adjust_font_size():
  display(HTML('''<style>
    body {
      font-size: 28px;
    }
  '''))

if adjust_font_size not in shell.events.callbacks['pre_execute']:
  shell.events.register('pre_execute', adjust_font_size)

# Sample string
text = "Hello, Python!"

# Finding the substring "Python"
index = text.find("Python")
print(index)  # Output: 7

# Finding a substring that doesn't exist
index = text.find("Java")
print(index)  # Output: -1

# Finding the substring "Python" within a range
index = text.find("Python", 0, 10)
print(index)  # Output: -1

# Finding the substring "Python" starting from index 7
index = text.find("Python", 7)
print(index)  # Output: 7