# -*- coding: utf-8 -*-
"""039-Python in a minute.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/124i0zkzBZSvQ4GlvVOhrFhr7_CFuctN6
"""

from IPython.display import HTML
shell = get_ipython()

def adjust_font_size():
  display(HTML('''<style>
    body {
      font-size: 28px;
    }
  '''))

if adjust_font_size not in shell.events.callbacks['pre_execute']:
  shell.events.register('pre_execute', adjust_font_size)

# Basic example with positional arguments
text = "Hello, {}!".format("Python")
print(text)  # Output: 'Hello, Python!'

# Multiple placeholders with positional arguments
text = "{} is {} years old.".format("Python", 30)
print(text)  # Output: 'Python is 30 years old.'

# Named placeholders with keyword arguments
text = "{name} is learning {language}.".format(name="Alice", language="Python")
print(text)  # Output: 'Alice is learning Python.'