# -*- coding: utf-8 -*-
"""040-Python in a minute.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1uwLURsKZ9w3k0M_wJ12jMb2cbLRkrZew
"""

from IPython.display import HTML
shell = get_ipython()

def adjust_font_size():
  display(HTML('''<style>
    body {
      font-size: 28px;
    }
  '''))

if adjust_font_size not in shell.events.callbacks['pre_execute']:
  shell.events.register('pre_execute', adjust_font_size)

# Sample dictionary
data = {"name": "Alice", "language": "Python"}

# Using format_map with a dictionary
text = "Hello, {name}! Welcome to {language}.".format_map(data)
print(text)  # Output: 'Hello, Alice! Welcome to Python.'

# Dictionary with additional information
data = {"name": "Alice", "language": "Python", "age": 30, "city": "Wonderland"}

# Using format_map with a subset of dictionary keys
text = "{name}, aged {age}, lives in {city} and loves {language}.".format_map(data)
print(text)  # Output: 'Alice, aged 30, lives in Wonderland and loves Python.'