# -*- coding: utf-8 -*-
"""041-Python in a minute.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1riVa3f6LzcjTvAR7ZyRbHn9R-qY35xPw
"""

from IPython.display import HTML
shell = get_ipython()

def adjust_font_size():
  display(HTML('''<style>
    body {
      font-size: 28px;
    }
  '''))

if adjust_font_size not in shell.events.callbacks['pre_execute']:
  shell.events.register('pre_execute', adjust_font_size)

# Sample string
text = "Hello, Python!"

# Finding the substring "Python"
index = text.index("Python")
print(index)  # Output: 7

# Using find() to search for a substring that doesn't exist
index_find = text.find("Java")
print(index_find)  # Output: -1

# Using index() to search for a substring that doesn't exist
try:
    index_index = text.index("Java")
except ValueError as e:
    print(e)  # Output: substring not found

# Finding the substring "Python" within a range
try:
    index = text.index("Python", 0, 10)
except ValueError as e:
    print(e)  # Output: substring not found

# Finding the substring "Python" starting from index 7
index = text.index("Python", 7)
print(index)  # Output: 7