# -*- coding: utf-8 -*-
"""042-Python in a minute.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1WS6OOXo_r_GOs5Kt_sVVeP5TsXJ-26G8
"""

from IPython.display import HTML
shell = get_ipython()

def adjust_font_size():
  display(HTML('''<style>
    body {
      font-size: 28px;
    }
  '''))

if adjust_font_size not in shell.events.callbacks['pre_execute']:
  shell.events.register('pre_execute', adjust_font_size)

# Sample strings
text1 = "Python3"

# Checking if the strings are alphanumeric
print(text1.isalnum())  # Output: True

# Sample strings
text2 = "Hello, World!"

# Checking if the strings are alphanumeric
print(text2.isalnum())  # Output: False

# Sample strings
text3 = "12345"

# Checking if the strings are alphanumeric
print(text3.isalnum())  # Output: True

# Sample strings
text4 = "123 45"

# Checking if the strings are alphanumeric
print(text4.isalnum())  # Output: False