# -*- coding: utf-8 -*-
"""044-Python in a minute.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1d7pHMO-vAGwkjIphPsdeVI867dD1-iRM
"""

from IPython.display import HTML
shell = get_ipython()

def adjust_font_size():
  display(HTML('''<style>
    body {
      font-size: 28px;
    }
  '''))

if adjust_font_size not in shell.events.callbacks['pre_execute']:
  shell.events.register('pre_execute', adjust_font_size)

# Check if all characters are ASCII
text = "Python"
print(text.isascii())  # Output: True

# String with non-ASCII characters
text = "Python™"
print(text.isascii())  # Output: False

text = "Python😊"
print(text.isascii())  # Output: False

# Empty string
text = ""
print(text.isascii())  # Output: True