# -*- coding: utf-8 -*-
"""045-Python in a minute.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ttvsRPZYXmbeXrEtyFZcNKpuX0UXXsMG
"""

from IPython.display import HTML
shell = get_ipython()

def adjust_font_size():
  display(HTML('''<style>
    body {
      font-size: 28px;
    }
  '''))

if adjust_font_size not in shell.events.callbacks['pre_execute']:
  shell.events.register('pre_execute', adjust_font_size)

# Check if all characters are decimal
text = "12345"
print(text.isdecimal())  # Output: True

# String with non-decimal characters
text = "12345.0"
print(text.isdecimal())  # Output: False

# String with superscript numbers
text = "⁰¹²³"
print(text.isdecimal())  # Output: False