# -*- coding: utf-8 -*-
"""047-Python in a minute.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1mIgWMt6d9I-DIGgw_J9YzxBOARegR5ei
"""

from IPython.display import HTML
shell = get_ipython()

def adjust_font_size():
  display(HTML('''<style>
    body {
      font-size: 28px;
    }
  '''))

if adjust_font_size not in shell.events.callbacks['pre_execute']:
  shell.events.register('pre_execute', adjust_font_size)

# Check if all characters are digits
text = "12345"
print(text.isdigit())  # Output: True

# String with non-digit characters
text = "12345.0"
print(text.isdigit())  # Output: False

# String with superscript numbers
text = "⁰¹²³"
print(text.isdigit())  # Output: True

# Compare isdigit() with isdecimal() for the same string
print(text.isdecimal())  # Output: False