# -*- coding: utf-8 -*-
"""048-Python in a minute.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1XJ9QQB81sskN2F9jB-xOXziFd8KvCOD0
"""

from IPython.display import HTML
shell = get_ipython()

def adjust_font_size():
  display(HTML('''<style>
    body {
      font-size: 28px;
    }
  '''))

if adjust_font_size not in shell.events.callbacks['pre_execute']:
  shell.events.register('pre_execute', adjust_font_size)

# Check if the string is a valid identifier
text = "variable1"
print(text.isidentifier())  # Output: True

# String starting with a digit
text = "1variable"
print(text.isidentifier())  # Output: False

# String with special characters
text = "var-new"
print(text.isidentifier())  # Output: False