# -*- coding: utf-8 -*-
"""049-Python in a minute.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Kk5eAfMNTxrvuGCOkibO3rLhTilN_Npp
"""

from IPython.display import HTML
shell = get_ipython()

def adjust_font_size():
  display(HTML('''<style>
    body {
      font-size: 28px;
    }
  '''))

if adjust_font_size not in shell.events.callbacks['pre_execute']:
  shell.events.register('pre_execute', adjust_font_size)

# Check if all cased characters are lowercase
text = "hello"
print(text.islower())  # Output: True

# String with mixed case characters
text = "Hello"
print(text.islower())  # Output: False

# String with lowercase letters, numbers, and special characters
text = "hello123!"
print(text.islower())  # Output: True