# -*- coding: utf-8 -*-
"""051-Python in a minute.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/11lfK2Y1cKH5lgTTw8iF4-GDD3sKWbWfE
"""

from IPython.display import HTML
shell = get_ipython()

def adjust_font_size():
  display(HTML('''<style>
    body {
      font-size: 28px;
    }
  '''))

if adjust_font_size not in shell.events.callbacks['pre_execute']:
  shell.events.register('pre_execute', adjust_font_size)

# Check if all characters are printable
text = "Hello, World!"
print(text.isprintable())  # Output: True

# String with non-printable characters
text = "Hello,\nWorld!"
print(text.isprintable())  # Output: False

# Empty string
text = ""
print(text.isprintable())  # Output: True