# -*- coding: utf-8 -*-
"""053-Python in a minute.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1-mmMYktkNrHGWQCQVTt0FJlC9bZBnmHb
"""

from IPython.display import HTML
shell = get_ipython()

def adjust_font_size():
  display(HTML('''<style>
    body {
      font-size: 28px;
    }
  '''))

if adjust_font_size not in shell.events.callbacks['pre_execute']:
  shell.events.register('pre_execute', adjust_font_size)

# Check if the string is title-cased
text = "Hello World"
print(text.istitle())  # Output: True

# String that is not title-cased
text = "hello World"
print(text.istitle())  # Output: False

# String with mixed casing within words
text = "Hello world Of Python"
print(text.istitle())  # Output: False