# -*- coding: utf-8 -*-
"""054-Python in a minute.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1-g2B1pAG69KkO4YWC7YSD69Iqv99QCI_
"""

from IPython.display import HTML
shell = get_ipython()

def adjust_font_size():
  display(HTML('''<style>
    body {
      font-size: 28px;
    }
  '''))

if adjust_font_size not in shell.events.callbacks['pre_execute']:
  shell.events.register('pre_execute', adjust_font_size)

# Check if all cased characters are uppercase
text = "HELLO"
print(text.isupper())  # Output: True

# String with mixed case characters
text = "Hello"
print(text.isupper())  # Output: False

# String with uppercase letters, numbers, and special characters
text = "HELLO123!"
print(text.isupper())  # Output: True