# -*- coding: utf-8 -*-
"""055-Python in a minute.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1-_2GyAL81SztbSAzVdLr5GAt_Kyf1da2
"""

from IPython.display import HTML
shell = get_ipython()

def adjust_font_size():
  display(HTML('''<style>
    body {
      font-size: 28px;
    }
  '''))

if adjust_font_size not in shell.events.callbacks['pre_execute']:
  shell.events.register('pre_execute', adjust_font_size)

# Concatenate list of words with a space as separator
words = ['Python', 'is', 'fun']
result = ' '.join(words)
print(result)  # Output: Python is fun

# Concatenate list of words with a hyphen as separator
result = '-'.join(words)
print(result)  # Output: Python-is-fun

# Concatenate tuple of numbers with a comma as separator
numbers = ('1', '2', '3')
result = ','.join(numbers)
print(result)  # Output: 1,2,3