# -*- coding: utf-8 -*-
"""056-Python in a minute.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1-XiKxg1rtG624x0h3CQh2Sfu3eb6XGpX
"""

from IPython.display import HTML
shell = get_ipython()

def adjust_font_size():
  display(HTML('''<style>
    body {
      font-size: 28px;
    }
  '''))

if adjust_font_size not in shell.events.callbacks['pre_execute']:
  shell.events.register('pre_execute', adjust_font_size)

# Left-justify string in a string of length 10
text = 'Python'
result = text.ljust(10)
print(f'"{result}"')  # Output: "Python    "

# Left-justify string in a string of length 10 with a different fill character
result = text.ljust(10, '-')
print(f'"{result}"')  # Output: "Python----"

# Left-justify longer string than specified width
text = 'Python is awesome'
result = text.ljust(10)
print(f'"{result}"')  # Output: "Python is awesome"