# -*- coding: utf-8 -*-
"""058-Python in a minute.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1-OawEQi-lqpX1YKrDyAnkV-8rk5SlDWg
"""

from IPython.display import HTML
shell = get_ipython()

def adjust_font_size():
  display(HTML('''<style>
    body {
      font-size: 28px;
    }
  '''))

if adjust_font_size not in shell.events.callbacks['pre_execute']:
  shell.events.register('pre_execute', adjust_font_size)

# Remove leading whitespace
text = "   Hello, World!"
result = text.lstrip()
print(result)  # Output: Hello, World!

# Remove specific leading characters
text = "...Hello, World!"
result = text.lstrip('.')
print(result)  # Output: Hello, World!

# Remove leading tabs and spaces
text = "\t   Hello, Python!"
result = text.lstrip()
print(result)  # Output: Hello, Python!