# -*- coding: utf-8 -*-
"""060-Python in a minute.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1-G72dzIWegO3p0EUctBltQh_gpc4SMIK
"""

from IPython.display import HTML
shell = get_ipython()

def adjust_font_size():
  display(HTML('''<style>
    body {
      font-size: 28px;
    }
  '''))

if adjust_font_size not in shell.events.callbacks['pre_execute']:
  shell.events.register('pre_execute', adjust_font_size)

# Split string at the first occurrence of a space
text = "Python is fun"
result = text.partition(' ')
print(result)  # Output: ('Python', ' ', 'is fun')

# Separator not found in the string
text = "hello world"
result = text.partition(',')
print(result)  # Output: ('hello world', '', '')