# -*- coding: utf-8 -*-
"""061-Python in a minute.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1-D1jrmtdK8EcWB7fx4WqveFYM5ggZ30s
"""

from IPython.display import HTML
shell = get_ipython()

def adjust_font_size():
  display(HTML('''<style>
    body {
      font-size: 28px;
    }
  '''))

if adjust_font_size not in shell.events.callbacks['pre_execute']:
  shell.events.register('pre_execute', adjust_font_size)

# Remove specified prefix
text = "HelloWorld"
result = text.removeprefix('Hello')
print(result)  # Output: World

# Compare with lstrip() to remove leading characters
text = "HHHi Python!"

result = text.lstrip('H')
print(result)  # Output: i Python!

result = text.removeprefix('H')
print(result)  # Output: HHi Python!

# Prefix not present in the string
text = "HelloWorld"
result = text.removeprefix('Hi')
print(result)  # Output: HelloWorld