# -*- coding: utf-8 -*-
"""062-Python in a minute.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1-9mMB67dXl48rOl4APo0YkRKSPDXistA
"""

from IPython.display import HTML
shell = get_ipython()

def adjust_font_size():
  display(HTML('''<style>
    body {
      font-size: 28px;
    }
  '''))

if adjust_font_size not in shell.events.callbacks['pre_execute']:
  shell.events.register('pre_execute', adjust_font_size)

# Remove suffix if present
text = "hello_world"
result = text.removesuffix('_world')
print(result)  # Output: hello

# Suffix not present
text = "hello_world"
result = text.removesuffix('_python')
print(result)  # Output: hello_world