# -*- coding: utf-8 -*-
"""063-Python in a minute.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1-3B1QSMf1vV0F13htbkfRgqwREdJhfQY
"""

from IPython.display import HTML
shell = get_ipython()

def adjust_font_size():
  display(HTML('''<style>
    body {
      font-size: 28px;
    }
  '''))

if adjust_font_size not in shell.events.callbacks['pre_execute']:
  shell.events.register('pre_execute', adjust_font_size)

# Simple replacement
text = "hello world"
result = text.replace('l', 'x')
print(result)  # Output: hexxo worxd

# Replacement with count parameter
text = "hello world"
result = text.replace('l', 'x', 1)
print(result)  # Output: hexlo world

# Multiple replacements
text = "hello hello hello"
result = text.replace('hello', 'hi')
print(result)  # Output: hi hi hi

# Multiple replacements with count
text = "hello hello hello"
result = text.replace('hello', 'hi', 2)
print(result)  # Output: hi hi hello