# -*- coding: utf-8 -*-
"""064-Python in a minute.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1-31Mq1K8YkS7zaiNDIpMHAMO0WPodaBI
"""

from IPython.display import HTML
shell = get_ipython()

def adjust_font_size():
  display(HTML('''<style>
    body {
      font-size: 28px;
    }
  '''))

if adjust_font_size not in shell.events.callbacks['pre_execute']:
  shell.events.register('pre_execute', adjust_font_size)

# Simple search
text = "hello world"
result = text.rfind('o')
print(result)  # Output: 7

# Comparing with find()
text = "hello world"
find_result = text.find('o')
rfind_result = text.rfind('o')
print(f"find(): {find_result}, rfind(): {rfind_result}")  # Output: find(): 4, rfind(): 7

# Search with start and end parameters
text = "hello world"
result = text.rfind('o', 0, 5)
print(result)  # Output: 4

# Substring not found
text = "hello world"
result = text.rfind('z')
print(result)  # Output: -1