# -*- coding: utf-8 -*-
"""065-Python in a minute.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1-24E_iOzorSRmtSqEONw8N8yNubJbOBs
"""

from IPython.display import HTML
shell = get_ipython()

def adjust_font_size():
  display(HTML('''<style>
    body {
      font-size: 28px;
    }
  '''))

if adjust_font_size not in shell.events.callbacks['pre_execute']:
  shell.events.register('pre_execute', adjust_font_size)

# Simple search
text = "hello world"
result = text.rindex('o')
print(result)  # Output: 7

# Search with start and end parameters
text = "hello world"
result = text.rindex('o', 0, 5)
print(result)  # Output: 4

# Substring not found
text = "hello world"
try:
    result = text.rindex('z')
except ValueError as e:
    print(e)  # Output: substring not found