# -*- coding: utf-8 -*-
"""066-Python in a minute.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1-0IHBa88WbM53wFVReAIjxydXlwtR8dQ
"""

from IPython.display import HTML
shell = get_ipython()

def adjust_font_size():
  display(HTML('''<style>
    body {
      font-size: 28px;
    }
  '''))

if adjust_font_size not in shell.events.callbacks['pre_execute']:
  shell.events.register('pre_execute', adjust_font_size)

# Simple right justification
text = "hello"
result = text.ljust(10)
print(f"'{result}'")  # Output: '     hello'

# Right justification with fill character
text = "hello"
result = text.rjust(10, '*')
print(f"'{result}'")  # Output: '*****hello'

# No padding needed
text = "hello"
result = text.rjust(5)
print(f"'{result}'")  # Output: 'hello'