# -*- coding: utf-8 -*-
"""067-Python in a minute.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1195GHBZGfZRzhVVt6aFdgi7WU_ocdlBz
"""

from IPython.display import HTML
shell = get_ipython()

def adjust_font_size():
  display(HTML('''<style>
    body {
      font-size: 28px;
    }
  '''))

if adjust_font_size not in shell.events.callbacks['pre_execute']:
  shell.events.register('pre_execute', adjust_font_size)

# Simple split at last occurrence
text = "hello world hello"
result = text.rpartition(' ')
print(result)  # Output: ('hello world', ' ', 'hello')

# Split at last occurrence with a different separator
text = "apple-banana-cherry"
result = text.rpartition('-')
print(result)  # Output: ('apple-banana', '-', 'cherry')

# Separator not found
text = "hello world"
result = text.rpartition('x')
print(result)  # Output: ('', '', 'hello world')