# -*- coding: utf-8 -*-
"""069-Python in a minute.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/10z-aWelSljDYSOnptjrmszvr6KID53rM
"""

from IPython.display import HTML
shell = get_ipython()

def adjust_font_size():
  display(HTML('''<style>
    body {
      font-size: 28px;
    }
  '''))

if adjust_font_size not in shell.events.callbacks['pre_execute']:
  shell.events.register('pre_execute', adjust_font_size)

# Simple split using whitespace
text = "hello world hello"
result = text.rsplit()
print(result)  # Output: ['hello', 'world', 'hello']

# Split with specified separator
text = "apple,banana,cherry"
result = text.rsplit(',')
print(result)  # Output: ['apple', 'banana', 'cherry']

# Split with maxsplit parameter
text = "apple,banana,cherry"
result = text.rsplit(',', 1)
print(result)  # Output: ['apple,banana', 'cherry']