# -*- coding: utf-8 -*-
"""070-Python in a minute.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/10fDK3Wb5PnQvMxARcXY2kfFrDQjJFLMg
"""

from IPython.display import HTML
shell = get_ipython()

def adjust_font_size():
  display(HTML('''<style>
    body {
      font-size: 28px;
    }
  '''))

if adjust_font_size not in shell.events.callbacks['pre_execute']:
  shell.events.register('pre_execute', adjust_font_size)

# Trailing whitespace removal
text = "hello world   "
result = text.rstrip()
print(f"'{result}'")  # Output: 'hello world'

# Removal of specific trailing characters
text = "hello world!!!"
result = text.rstrip('!')
print(f"'{result}'")  # Output: 'hello world'

# No characters removed
text = "hello world!!!"
result = text.rstrip('d')
print(f"'{result}'")  # Output: 'hello world!!!'

