# -*- coding: utf-8 -*-
"""072-Python in a minute.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/10WSSWXU1DvLMdXr9R72P9FX8HQybajoj
"""

from IPython.display import HTML
shell = get_ipython()

def adjust_font_size():
  display(HTML('''<style>
    body {
      font-size: 28px;
    }
  '''))

if adjust_font_size not in shell.events.callbacks['pre_execute']:
  shell.events.register('pre_execute', adjust_font_size)

# Check if string starts with specified prefix
text = "hello"
result = text.startswith('he')
print(result)  # Output: True

# Check with start argument
result = text.startswith('e', 1)
print(result)  # Output: True

# Check with start and end arguments
result = text.startswith('el', 1, 4)
print(result)  # Output: True