# -*- coding: utf-8 -*-
"""073-Python in a minute.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/10TrldHMoFURGABqizDJlecNRDaNyOQfp
"""

from IPython.display import HTML
shell = get_ipython()

def adjust_font_size():
  display(HTML('''<style>
    body {
      font-size: 28px;
    }
  '''))

if adjust_font_size not in shell.events.callbacks['pre_execute']:
  shell.events.register('pre_execute', adjust_font_size)

text = "hello World"
print(text.capitalize())  # Output: Hello world

text = "HEllo"
print(text.lower())  # Output: hello

text = "HELLO"
print(text.casefold())  # Output: hello

text = "hello world"
print(text.split(' '))  # Output: ['hello', 'world']

text = "hello world of python programming"
print(text.rsplit(' ', 1))  # Output: ['hello world of python', 'programming']

print(text.rsplit(' ', 3))  # Output: ['hello world', 'of', 'python', 'programming']

text = "hello\nworld"
print(text.splitlines())  # Output: ['hello', 'world']

text = "hello world"
print(text.count('l'))  # Output: 3

text = "hello world"
print(text.replace('world', 'there'))  # Output: hello there

text = "hello\tworld"
print(text.expandtabs(4))  # Output: hello   world

text = "hello world"
print(text.encode('utf-8'))  # Output: b'hello world'

text = "hello world, wellcome world of python"
print(text.find('world'))  # Output: 6

text = "hello world, wellcome world of python"
print(text.rfind('world'))  # Output: 22

text ="hello world, wellcome world of python"
print(text.index('world'))  # Output: 6

text ="hello world, wellcome world of python"
print(text.rindex('world'))  # Output: 22

text ="hello world, wellcome world of python"

print(text.find('Python'))  # Output: 6

print(text.index('Python'))  # Output: 6

text = "hello world"
print(text.startswith('hello'))  # Output: True

text = "hello world"
print(text.endswith('world'))  # Output: True

text = "hello123"
print(text.isalnum())  # Output: True

text = "hello123?"
print(text.isalnum())  # Output: False

text = "hello"
print(text.isalpha())  # Output: True

text = "hello1"
print(text.isalpha())  # Output: False

text = "hello"
print(text.isascii())  # Output: True

text = "hello🕵️‍♀️"
print(text.isascii())  # Output: False

text = "234"
print(text.isdecimal())
print(text.isdigit())
print(text.isnumeric())

# String with superscript numbers
text = "²³⁴"
print(text.isdecimal())
print(text.isdigit())
print(text.isnumeric())

# String with a fraction
text = "⅓"
print(text.isdecimal())
print(text.isdigit())
print(text.isnumeric())

text = "variable1"
print(text.isidentifier())  # Output: True

text = "1variable"
print(text.isidentifier())  # Output: False

text = "Hello World"
print(text.istitle())  # Output: True

text = "HELLO"
print(text.isupper())  # Output: True

text = "Hello"
print(text.isupper())  # Output: False

text = "hello"
print(text.islower())  # Output: True

text = "Hello"
print(text.islower())  # Output: False

text = "hello world"
print(text.isprintable())  # Output: True

text = "hello\nworld"
print(text.isprintable())  # Output: False

text = "   "
print(text.isspace())  # Output: True

text = " \n\t  "
print(text.isspace())  # Output: True

text = "Hello, {}!".format("world")
print(text)  # Output: Hello, world!

text = "Hello, {name}!".format_map({"name": "world"})
print(text)  # Output: Hello, world!

text = ", ".join(["hello", "world"])
print(text)  # Output: hello, world

text = "hello".center(11, '-')
print(text)  # Output: ---hello---

text = "hello".ljust(10, '-')
print(text)  # Output: hello-----

text = "hello".rjust(10, '-')
print(text)  # Output: -----hello

text = "   hello"
print(text.lstrip())  # Output: hello

text = "hello   "
print(text.rstrip())  # Output: hello

text = "hello world"
print(text.partition(' '))  # Output: ('hello', ' ', 'world')

text = "hello world world"
print(text.rpartition(' '))  # Output: ('hello world', ' ', 'world')

text = "hello world"
print(text.removeprefix('hello '))  # Output: world

text = "hello world"
print(text.removesuffix(' world'))  # Output: hello