# -*- coding: utf-8 -*-
"""074-Python in a minute.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1y-DiUFqhOoOZu1iSC25K4zGWMBtnLYiF
"""

from IPython.display import HTML
shell = get_ipython()

def adjust_font_size():
  display(HTML('''<style>
    body {
      font-size: 28px;
    }
  '''))

if adjust_font_size not in shell.events.callbacks['pre_execute']:
  shell.events.register('pre_execute', adjust_font_size)

# Embedding variables
name = "Alice"
result = f"Hello, {name}!"
print(result)

# Using arithmetic expressions
result = f"{2 + 2}"
print(result)

# Calling functions
def greet():
    return "Hello"

result = f"{greet()}!"
print(result)

