# -*- coding: utf-8 -*-
"""075-Python in a minute.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1vawX7cz6rwKhoD8sdq1x0BKxZgD2c8cJ
"""

from IPython.display import HTML
shell = get_ipython()

def adjust_font_size():
  display(HTML('''<style>
    body {
      font-size: 28px;
    }
  '''))

if adjust_font_size not in shell.events.callbacks['pre_execute']:
  shell.events.register('pre_execute', adjust_font_size)

# Floating-point number with 2 decimal places
value = 3.14159
result = f"{value:.2f}"
print(result)

# Right-align in a field of width 10
value = "Python"
result = f"{value:>10}"
print(result)

# Include a plus sign for positive numbers
value = 42
result = f"{value:+}"
print(result)