# -*- coding: utf-8 -*-
"""076-Python in a minute.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/18QsSsXRd_XSogYNryUPNzukK0ulPrSgl
"""

from IPython.display import HTML
shell = get_ipython()

def adjust_font_size():
  display(HTML('''<style>
    body {
      font-size: 28px;
    }
  '''))

if adjust_font_size not in shell.events.callbacks['pre_execute']:
  shell.events.register('pre_execute', adjust_font_size)

"""# **What is Regex?**

A regular expression is a sequence of characters that forms a search pattern.

You can use regex to check if a string contains the specified search pattern,

replace text, or split a string based on a pattern.

# **Python's re Module**

Python provides the re module to work with regular expressions.

Some of the most important methods in this module:
"""

import re
result = re.match(r'hello', 'hello world')
result = re.search(r'world', 'hello world')
result = re.findall(r'o', 'hello world')
result = re.finditer(r'o', 'hello world')
result = re.sub(r'world', 'Python', 'hello world')
result = re.split(r'\s', 'hello world')
pattern = re.compile(r'hello')