# -*- coding: utf-8 -*-
"""078-Python in a minute.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1T1nr3UpcPd3WGiEUxUclIq6qxSRnZEYB
"""

from IPython.display import HTML
shell = get_ipython()

def adjust_font_size():
  display(HTML('''<style>
    body {
      font-size: 20px;
    }
  '''))

if adjust_font_size not in shell.events.callbacks['pre_execute']:
  shell.events.register('pre_execute', adjust_font_size)

# re.search(pattern, string, flags=0)

import re

text = "hello world"
result = re.search(r'world', text)
print(result)

text = "hello world"
result = re.search(r'Python', text)
print(result)

text = "hello world"
result = re.match(r'world', text)
print(result)

result = re.search(r'world', text)
print(result)

