# -*- coding: utf-8 -*-
"""081-Python in a minute.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1IRSR2QGCRYtdrlL6GE01vfH2_kTNLECo
"""

from IPython.display import HTML
shell = get_ipython()

def adjust_font_size():
  display(HTML('''<style>
    body {
      font-size: 20px;
    }
  '''))

if adjust_font_size not in shell.events.callbacks['pre_execute']:
  shell.events.register('pre_execute', adjust_font_size)

# re.finditer(pattern, string, flags=0)

import re

# Finding all matches
text = "hello world hello"
result = re.finditer(r'hello', text)
for match in result:
    print(match)

# Finding digits
text = "abc 123 def 456"
result = re.finditer(r'\d+', text)
for match in result:
    print(match)

# Using flags for case-insensitive search
text = "Python is great. I love python."
result = re.finditer(r'python', text, re.IGNORECASE)
for match in result:
    print(match)

