# -*- coding: utf-8 -*-
"""082-Python in a minute.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1wZJ9xlBze_siD1ur22u0Ao1mfTvHtRy-
"""

from IPython.display import HTML
shell = get_ipython()

def adjust_font_size():
  display(HTML('''<style>
    body {
      font-size: 20px;
    }
  '''))

if adjust_font_size not in shell.events.callbacks['pre_execute']:
  shell.events.register('pre_execute', adjust_font_size)

# re.sub(pattern, repl, string, count=0, flags=0)

import re

# Simple replacement
text = "hello world"
result = re.sub(r'hello', 'hi', text)
print(result)

# Replace digits with '#'
text = "abc 123 def 456"
result = re.sub(r'\d+', '#', text)
print(result)

# Case-insensitive replacement
text = "Python is great. I love python."
result = re.sub(r'python', 'JavaScript', text, flags=re.IGNORECASE)
print(result)

