# -*- coding: utf-8 -*-
"""083-Python in a minute.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1hvN6qpfOmecJbzh1DHmXG1sWOfus2W29
"""

from IPython.display import HTML
shell = get_ipython()

def adjust_font_size():
  display(HTML('''<style>
    body {
      font-size: 20px;
    }
  '''))

if adjust_font_size not in shell.events.callbacks['pre_execute']:
  shell.events.register('pre_execute', adjust_font_size)

#re.split(pattern, string, maxsplit=0, flags=0)

import re

# Simple split by spaces
text = "hello world hello"
result = re.split(r'\s+', text)
print(result)

# Split by digits
text = "abc123def456"
result = re.split(r'\d+', text)
print(result)

# Case-insensitive split by 'python'
text = "Python is great. I love python."
result = re.split(r'python', text, flags=re.IGNORECASE)
print(result)

