# -*- coding: utf-8 -*-
"""084-Python in a minute.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1I0qmo0tmR5Wwmu6_J_vcMTqYdNcDbV-Y
"""

from IPython.display import HTML
shell = get_ipython()

def adjust_font_size():
  display(HTML('''<style>
    body {
      font-size: 20px;
    }
  '''))

if adjust_font_size not in shell.events.callbacks['pre_execute']:
  shell.events.register('pre_execute', adjust_font_size)

# re.compile(pattern, flags=0)

import re

# Compile pattern and search
pattern = re.compile(r'hello')
text = "hello world"
result = pattern.search(text)
print(result)

# Compile pattern and find all digits
pattern = re.compile(r'\d+')
text = "abc 123 def 456"
result = pattern.findall(text)
print(result)

# Compile case-insensitive pattern and search
pattern = re.compile(r'python', re.IGNORECASE)
text = "Python is great. I love python."
result = pattern.findall(text)
print(result)

