# -*- coding: utf-8 -*-
"""085-Python in a minute.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/19qIphgxvYaqXf9aF1o8-giheGLEh9i3m
"""

from IPython.display import HTML
shell = get_ipython()

def adjust_font_size():
  display(HTML('''<style>
    body {
      font-size: 20px;
    }
  '''))

if adjust_font_size not in shell.events.callbacks['pre_execute']:
  shell.events.register('pre_execute', adjust_font_size)

import re

# Example 1: Search for the character 'a'
text = "abc123"
result = re.search(r'a', text)
print(result)

# Example 2: Search for the sequence 'abc'
result = re.search(r'abc', text)
print(result)

# Example 3: Case sensitivity - Search for 'A'
result = re.search(r'A', text)
print(result)

