# -*- coding: utf-8 -*-
"""086-Python in a minute.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1EwI14DVNRrLE69sktJ5luY8_9wfwJnr1
"""

from IPython.display import HTML
shell = get_ipython()

def adjust_font_size():
  display(HTML('''<style>
    body {
      font-size: 20px;
    }
  '''))

if adjust_font_size not in shell.events.callbacks['pre_execute']:
  shell.events.register('pre_execute', adjust_font_size)

# Dot .:

# Pattern: h.llo

# Matches:
'hello'
'hallo'
'hxllo'
# Does not match:
'hllo'
'heello'

# Caret ^ (start of string):

# Pattern: ^hello

# Matches:
'hello world'
# Does not match:
'world hello'
'hi hello'

# Dollar sign $ (end of string):

# Pattern: world$

# Matches:
'hello world'
# Does not match:
'world hello'
'hello world!'