# -*- coding: utf-8 -*-
"""088-Python in a minute.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Ww-BbhWQGfeEzT04J99fGx7s_yDRd69Y
"""

from IPython.display import HTML
shell = get_ipython()

def adjust_font_size():
  display(HTML('''<style>
    body {
      font-size: 20px;
    }
  '''))

if adjust_font_size not in shell.events.callbacks['pre_execute']:
  shell.events.register('pre_execute', adjust_font_size)

# Curly braces {n}:

# Pattern: a{3}
# Matches:
'aaa' (exactly 3 'a's)
# Does not match:
'aa' (less than 3 'a's)
'aaaa' (more than 3 'a's)

# Curly braces {n,}:

# Pattern: a{2,}
# Matches:
'aa' (2 'a's)
'aaa' (3 'a's)
'aaaa' (4 'a's)
# and more (2 or more 'a's)
# Does not match:
'a' (less than 2 'a's)
Curly braces {n,m}:

# Pattern: a{2,4}
# Matches:
'aa' (2 'a's)
'aaa' (3 'a's)
'aaaa' (4 'a's)
# Does not match:
'a' (less than 2 'a's)
'aaaaa' (more than 4 'a's)