# -*- coding: utf-8 -*-
"""090-Python in a minute.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1RWulbIHV2sR8ndYixR_S8dPgUkTcTD1Y
"""

from IPython.display import HTML
shell = get_ipython()

def adjust_font_size():
  display(HTML('''<style>
    body {
      font-size: 20px;
    }
  '''))

if adjust_font_size not in shell.events.callbacks['pre_execute']:
  shell.events.register('pre_execute', adjust_font_size)

# Square brackets [abc]:

# Pattern: [abc]
# Matches:
# 'a' (one of the characters in the set)
# 'b' (one of the characters in the set)
# 'c' (one of the characters in the set)
# Does not match:
# 'd' (not in the set)
# 'e' (not in the set)

# Square brackets with caret [^abc]:

# Pattern: [^abc]
# Matches:
# 'd' (not 'a', 'b', or 'c')
# 'e' (not 'a', 'b', or 'c')
# 'f' (not 'a', 'b', or 'c')
# Does not match:
# 'a' (in the set)
# 'b' (in the set)
# 'c' (in the set)

# Square brackets with range [a-z]:

# Pattern: [a-z]
# Matches:
# 'a' (in the range 'a' to 'z')
# 'b' (in the range 'a' to 'z')
# 'c' (in the range 'a' to 'z')
# and so on up to 'z'
# Does not match:
# 'A' (not in the range 'a' to 'z')
# '1' (not in the range 'a' to 'z')