# -*- coding: utf-8 -*-
"""091-Python in a minute.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1zj2iPjCvCIBaR1Qg42qOxKk3ddfsP30c
"""

from IPython.display import HTML
shell = get_ipython()

def adjust_font_size():
  display(HTML('''<style>
    body {
      font-size: 20px;
    }
  '''))

if adjust_font_size not in shell.events.callbacks['pre_execute']:
  shell.events.register('pre_execute', adjust_font_size)

# Capturing group (...):

# Pattern: (abc)
# Matches:
# 'abc' (captures 'abc')
# Does not match:
# 'ab' (does not match the entire pattern)
# 'abcd' (matches 'abc' and leaves 'd')

# Non-capturing group (?:...):

# Pattern: (?:abc)
# Matches:
# 'abc' (does not capture)
# Does not match:
# 'ab' (does not match the entire pattern)
# 'abcd' (matches 'abc' and leaves 'd')

# Alternation |:

# Pattern: a|b
# Matches:
# 'a' (matches 'a')
# 'b' (matches 'b')
# Does not match:
# 'c' (does not match either 'a' or 'b')