# -*- coding: utf-8 -*-
"""092-Python in a minute.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1TSHEl5mevpE3YJa0fUUb8UpTOCEMyAb5
"""

from IPython.display import HTML
shell = get_ipython()

def adjust_font_size():
  display(HTML('''<style>
    body {
      font-size: 20px;
    }
  '''))

if adjust_font_size not in shell.events.callbacks['pre_execute']:
  shell.events.register('pre_execute', adjust_font_size)

Positive lookahead (?=...):

Pattern: a(?=b)
Matches:
'a' in 'ab' (followed by 'b')
Does not match:
'a' in 'ac' (not followed by 'b')

Negative lookahead (?!...):

Pattern: a(?!b)
Matches:
'a' in 'ac' (not followed by 'b')
Does not match:
'a' in 'ab' (followed by 'b')

Positive lookbehind (?<=...):

Pattern: (?<=a)b
Matches:
'b' in 'ab' (preceded by 'a')
Does not match:
'b' in 'cb' (not preceded by 'a')

Negative lookbehind (?<!...):

Pattern: (?<!a)b
Matches:
'b' in 'cb' (not preceded by 'a')
Does not match:
'b' in 'ab' (preceded by 'a')